<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityRepository;

/**
 * BooksRepository
 *
 * This is a Doctrine Entity repository class. This is a class that holds methods that query the database,
 * the Doctrine service auto-generates the class but there are no methods generated, these must be customised.
 * It is related to a Doctrine Entity class.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{
    /**
     * @param $request
     *
     * @return mixed
     */
    public function findAllBooksMatchingSearch(Request $request)
    {
        return $this->createQueryBuilder('books')//alias for the table
            ->Where('books.author = :author')//avoid SQL injection by using placeholders
            ->setParameter('author', '%'.$request->get('author').'%' )//fill in the value
            ->orWhere('books.title = :title')
            ->setParameter('title', '%'.$request->get('title').'%')
            ->orWhere('books.catagory = :catagory')
            ->setParameter('catagory', '%'.$request->get('catagory').'%')
            ->getQuery()
            ->execute();
    }

    /*
     * test the search query using a predefined value
     */
    public function findAllFiction()
    {
        return $this->createQueryBuilder('books')//alias for the table
            ->andWhere('books.catagory = :catagory')//avoid SQL injection by using placeholders
            ->setParameter('catagory', 'fiction')//fill in a predefined value
            ->getQuery()//build the query
            ->execute();//execute the SQL query
    }
}
