<?php

namespace AppBundle\Repository;

/**
 * LoansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoansRepository extends \Doctrine\ORM\EntityRepository
{
}
