<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This is a Doctrine Entity repository class. This is a class that holds methods that query the database,
 * the Doctrine service auto-generates the class but there are no methods generated, these must be customised.
 * It is related to a Doctrine Entity class.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

}
