app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

about:
    path: /about
    defaults:
        _controller: AppBundle:Main:about