security:
    encoders:
        # tells the system what method to use to encrypt items for the User entity
        AppBundle\Entity\User: bcrypt

    providers:
        # set up how users are defined
        users:
            entity: {class: AppBundle\Entity\User, property: username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # set up the authenticator service to handle login requests
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            # logout service
            logout:
                path: /logout



