# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#   use the login as a service that can be called on.
#   autowire is used because the arguments in the constructor
#   for the class are typehinted and so arguments do not need
#   to be set explicitly here
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
